[package]
name = "mokume-normalization"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
description = "Normalization algorithms for mokume"

[lints]
workspace = true

[dependencies]
mokume-core = { path = "../mokume-core" }
