"""Concise descriptions for workflow flags shown in Mokume Studio."""

from __future__ import annotations


PARAMETER_HELP: dict[tuple[str, ...], dict[str, str]] = {
    ("quantify", "features2proteins"): {
        "msstats": "MSstats CSV input; requires SDRF metadata.",
        "output": "Output protein-intensity CSV.",
        "sdrf": "SDRF sample metadata; required by metadata-aware analysis options.",
        "min_aa": "Minimum peptide length in amino acids.",
        "fasta": "FASTA database; required for piBAQ.",
        "pibaq_enzyme": "Protease used for in-silico digestion.",
        "pibaq_max_aa": "Maximum theoretical peptide length.",
        "pibaq_min_shared": "Shared peptides needed to discover a protein family.",
        "pibaq_families_yaml": "YAML file with explicit protein-family overrides.",
        "pibaq_min_anchors": "Unique-peptide anchors required for proportional allocation.",
        "directlfq_min_nonan": "Minimum non-missing values for DirectLFQ.",
        "directlfq_num_samples_quadratic": "Maximum samples used for quadratic alignment.",
        "export_peptides": "Write normalized peptide intensities.",
        "export_ions": "Write normalized DirectLFQ ion intensities.",
        "batch_correction": "Enable ComBat batch correction.",
        "batch_method": "Read batch labels from sample prefixes or an SDRF column.",
        "batch_column": "SDRF column containing batch labels.",
        "batch_covariate": "SDRF covariate to preserve; may be repeated.",
        "batch_nonparametric": "Use non-parametric ComBat.",
        "batch_mean_only": "Correct batch means without scaling variances.",
        "batch_ref": "Reference batch label for ComBat.",
        "irs_reference_sample": "Reference sample name; may be repeated.",
        "irs_sdrf_column": "SDRF column used to identify references.",
        "irs_sdrf_value": "Reference value in the SDRF column; may be repeated.",
        "irs_reference_regex": "Regex used to auto-detect reference samples.",
        "irs_stat": "Statistic used for each plex reference.",
        "irs_remove_reference": "Remove reference samples from the output.",
        "coverage_threshold": "Minimum observed fraction within each condition.",
        "ratio_fraction_merge": "Method for merging fractions in ratio quantification.",
        "impute_method": "Method used to fill missing intensities.",
        "impute_quantile": "Detection-limit quantile for MinProb or MinDet.",
        "impute_shift": "MinProb distribution shift in standard deviations.",
        "impute_scale": "MinProb distribution scale factor.",
        "impute_n_neighbors": "Neighbour count for KNN or SeqKNN.",
        "de_contrast": "Condition pair to compare; may be repeated.",
        "de_contrast_file": "TSV file with group1 and group2 columns.",
        "de_method": "Differential-expression method.",
        "de_ensemble_method": "Ensemble member method; may be repeated.",
        "de_log2fc_threshold": "Minimum absolute log2 fold change, or auto.",
        "de_effect_size_gate": "Data-driven effect-size gate.",
        "de_fdr_threshold": "Maximum false discovery rate.",
        "de_fdr_method": "Multiple-testing correction method.",
        "de_output": "Output differential-expression results.",
        "threads": "Rust worker-thread count.",
    },
    ("quantify", "features2peptides"): {
        "parquet": "Feature-level QPX parquet input.",
        "sdrf": "SDRF sample metadata.",
        "min_aa": "Minimum peptide length in amino acids.",
        "min_unique": "Minimum unique peptides per protein.",
        "keep_shared_peptides": "Keep shared peptides and skip the unique-peptide gate.",
        "remove_ids": "File containing protein IDs to exclude.",
        "remove_decoy_contaminants": "Remove decoy and contaminant entries.",
        "remove_low_frequency_peptides": "Remove peptides detected in under 20% of samples.",
        "output": "Output normalized peptide intensities.",
        "skip_normalization": "Skip run- and sample-level normalization.",
        "run_normalization": "Run-level normalization method.",
        "sample_normalization": "Sample-level normalization method.",
        "log2": "Log2-transform output intensities.",
        "save_parquet": "Also write a parquet copy of the output.",
        "irs_channel": "Explicit pooled or reference channel label.",
        "irs_autodetect_regex": "Regex used to find reference channels in the SDRF.",
        "irs_stat": "Statistic used for each IRS reference.",
        "irs_scope": "Apply IRS globally, by mixture, or in two stages.",
        "aggregation_level": "Aggregate peptide values by sample or technical run.",
        "filter_config": "YAML or JSON preprocessing-filter configuration.",
        "generate_filter_config": "Write an example filter configuration and exit.",
        "filter_min_intensity": "Minimum accepted feature intensity.",
        "filter_cv_threshold": "Maximum coefficient of variation across replicates.",
        "filter_charge_state": "Accepted peptide charge state; may be repeated.",
        "filter_max_missed_cleavages": "Maximum accepted missed cleavages.",
        "filter_peptide_fdr": "Maximum peptide-level QPX q-value.",
        "filter_exclude_modification": "Modification to exclude; may be repeated.",
        "filter_protein_fdr": "Maximum protein-group QPX q-value.",
        "filter_min_features": "Minimum identified features per run.",
        "filter_max_missing_rate": "Maximum missing-feature fraction per technical run.",
    },
    ("quantify", "peptides2protein"): {
        "fasta": "FASTA database; required for piBAQ.",
        "peptides": "Normalized peptide-intensity input.",
        "enzyme": "Protease used for in-silico digestion.",
        "normalize": "Normalize protein quantification values.",
        "min_aa": "Minimum theoretical peptide length.",
        "max_aa": "Maximum theoretical peptide length.",
        "tpa": "Calculate total protein approach values for piBAQ.",
        "ruler": "Apply the proteomic ruler to piBAQ values.",
        "ploidy": "Cell ploidy used by the proteomic ruler.",
        "organism": "Organism used for histone annotations.",
        "cpc": "Cellular protein concentration in g/L.",
        "output": "Output protein-quantification file.",
        "qc_report": "Output path for the piBAQ QC PDF.",
        "directlfq_min_nonan": "Minimum non-missing values for DirectLFQ.",
        "families_yaml": "YAML file with explicit protein-family overrides.",
        "min_shared": "Shared peptides needed to discover a protein family.",
        "min_anchors": "Unique-peptide anchors required for proportional allocation.",
        "high_anchor_threshold": "Anchors per member required for high-confidence evidence.",
    },
    ("correct-batches",): {
        "input": "Directory containing protein-quantification TSV files.",
        "pattern": "Glob used to select input files.",
        "comment": "Prefix marking comment lines.",
        "sep": "Input field separator.",
        "output": "Output batch-corrected table.",
        "sample_id_column": "Column containing sample IDs.",
        "protein_id_column": "Column containing protein IDs.",
        "pibaq_raw_column": "Column containing raw piBAQ values.",
        "pibaq_corrected_column": "Name for corrected piBAQ values.",
        "export_anndata": "Also export the matrices as AnnData h5ad.",
    },
    ("tissuemap",): {
        "input": "Directory containing tissue-proteomics datasets.",
        "outdir": "Output directory for atlas tables and plots.",
        "config": "Optional TissueMap YAML configuration; form values override it.",
        "tmt_dataset": "Dataset ID to treat as TMT; may be repeated.",
        "threads": "Parallel worker count.",
        "dpi": "Resolution of generated plots.",
        "impute_method": "Missing-value method used before embedding.",
        "embedding_method": "Dimensionality-reduction method.",
    },
    ("plot", "pca"): {
        "protein_matrix": "Protein-intensity CSV input.",
        "sdrf": "SDRF metadata used to colour samples by condition.",
        "output": "Output PCA image.",
    },
    ("plot", "tsne"): {
        "input": "Directory containing protein tables.",
        "pattern": "Glob used to select protein tables.",
        "output": "Output t-SNE PDF.",
    },
    ("plot", "de"): {
        "protein_matrix": "Protein-intensity CSV input.",
        "outdir": "Output directory for DE plots.",
        "sdrf": "SDRF metadata; required for heatmap annotations.",
        "volcano": "Generate a volcano plot for each contrast.",
        "heatmap": "Generate a heatmap for each contrast.",
        "contrast": "Output key, two condition labels, and DE result CSV; may repeat.",
        "log2fc": "Minimum absolute log2 fold change.",
        "fdr": "Maximum adjusted p-value.",
        "highlight_protein": "Protein to highlight in volcano plots; may be repeated.",
    },
    ("interactive-report",): {
        "protein_matrix": "Protein-intensity CSV input.",
        "sdrf": "SDRF sample metadata.",
        "output": "Output HTML file; contrast keys are appended for multiple contrasts.",
        "contrast": "Output key, two condition labels, and DE result CSV; may repeat.",
        "log2fc": "Minimum absolute log2 fold change.",
        "fdr": "Maximum adjusted p-value.",
        "highlight_protein": "Protein to highlight; may be repeated.",
    },
}
